### ISSUE TITLE
Crosshair instead of hand?

### ISSUE THREAD

**Issue by jobspierings** [picturae/GeoReferencer#3]
When adding reference points to maps the 👆as mouse icon seems to be imprecise. When adding these points could this be ✛ or ╳ ?

**Comment by thomasvanmaaren** [comment]
Do you mean instead of the circular marker?

**Comment by jobspierings** [comment]
We do not see a circular marker - the app changes the mouse pointer from an arrow to a hand:

![image](https://cloud.githubusercontent.com/assets/5601623/11739064/c6b5bbda-9fe8-11e5-948b-a48975bba846.png)

A (transparent) circular crosshair might also be a fix.

**Comment by thomasvanmaaren** [comment]
ok thanks

**Comment by thomasvanmaaren** [comment]
added
