### ISSUE TITLE
Preview button gives error

### ISSUE THREAD

**Issue by jobspierings** [picturae/GeoReferencer#4]
Following instructions in [readme.md](https://github.com/picturae/GeoReferencer/blob/master/README.md) GeoReferencer is up and running. When using [preview] or [finish] an error occurs:

![schermafbeelding 2015-12-02 om 13 02 48](https://cloud.githubusercontent.com/assets/5601623/11559695/2ec28246-99bb-11e5-83c5-3e5a07a50337.png)

Full error message:

> {"data":null,"status":-1,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"http://georeferencer-api.dev/preview","data":{"referencePoints":[{"tileCoordinatesX":1540,"tileCoordinatesY":1092,"geoCoordinatesX":-48.075313568115234,"geoCoordinatesY":-15.844774624364414},{"tileCoordinatesX":1772,"tileCoordinatesY":876,"geoCoordinatesX":-48.0681037902832,"geoCoordinatesY":-15.813395760460585},{"tileCoordinatesX":1856,"tileCoordinatesY":1844,"geoCoordinatesX":-48.012657165527344,"geoCoordinatesY":-15.884899431747536}],"image":"http://georeferencer-api.dev/file/74eb1be2cb7c35a10d7be2475961ebfe/jpg","storeName":"d1901af501054207b3e0172c1b71da75"},"headers":{"Accept":"application/json, text/plain, _/_","Content-Type":"application/json;charset=utf-8"}},"statusText":""}

**Comment by dthornley** [comment]
Wrong commit message.

**Comment by jobspierings** [comment]
Is the issue clear or is further debugging necessary?

**Comment by thomasvanmaaren** [comment]
this issues is clear no further debugging required

**Comment by thomasvanmaaren** [comment]
https://github.com/picturae/GeoReferencer/commit/211999c0fedf0f8aed7176f640b8db0178cba108
