### ISSUE TITLE
addition to readme.md

### ISSUE THREAD

**Issue by jobspierings** [picturae/GeoReferencer#6]
Suggest to add following introductory text to readme.md:
# GeoReferencer

An open source, stand-alone web application for georeferencing images, with very simple interface. GeoReferencer converts (scanned) images of maps (JPEG, TIFF, PNG) to GeoTIFF by allowing the user to select reference points on current maps (OpenStreetMap, Google Map or custom).

Developed by [Picturae B.V.](https://picturae.com/) for the project [Erfgoed & Locatie](http://erfgoedenlocatie.nl/) ("Heritage and Location").

[_add screenshot(s) here_]

**Comment by thomasvanmaaren** [comment]
added
